### ISSUE TITLE
Edge 41 EdgeHTML 16 catalyst-toggle-switch error

### ISSUE THREAD

**Issue by OzBob** [catalyst/CatalystElementsBundle#5]
https://catalyst.github.io/CatalystElementsBundle/#/elements/catalyst-toggle-switch/demos/styled

https://catalyst.github.io/CatalystElementsBundle/#/elements/catalyst-toggle-switch/demos/basic

no physical movement of the toggle

**Comment by RebeccaStevens** [comment]
Hi @OzBob,
Thanks for the bug report.
Could you please open this issue on the [catalyst-toggle-switch repo](https://github.com/catalyst/catalyst-toggle-switch/issues/new)?

**Comment by RebeccaStevens** [comment]
Closing as this is now being tracked at catalyst/catalyst-toggle-switch#3
